# Generated by Django 4.1.12 on 2024-01-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuneTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='artist',
        ),
    ]
